export const RouteLink = {
  MAIN: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FIND_ID: '/find-id',
  FIND_PW: '/find-pw',
  SOCIAL: '/social/:page',
  SOCIAL_DETAIL: '/social/show/:id',
  NEWS: '/news',
  POSTS: '/post',
  TOOLS: '/tools',
  CHAT: '/chat/*',
  NOTICE: '/notice',
  NOTICE_WRITE: '/notice/write',
  NOTICE_DETAIL: '/notice/:id',
  NOTICE_EDIT: '/notice/edit/:id',
  FAQ: '/faq',
  TERMS: '/terms',
  MYPAGE: '/mypage',
  NOTIFICATIONS: '/mypage/notifications',
  ADMIN: '/admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_MEMBERS: '/admin/members',
  ADMIN_POSTS: '/admin/posts',
  ADMIN_SYSTEM: '/admin/system',
  ADMIN_APIS: '/admin/apis',
  ADMIN_TEST: '/admin/test',
  FORBIDDEN: '/forbidden',
  DEFAULT: '*',
};

export default RouteLink;
